### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by Sacolle** [Sacolle/Gamejam#2]
Fazer com que, quando a tecla `esc` for apertada, o jogo pause e uma tela com opções de pause apareça. 

Estilização a denifinir

**Comment by beersprite** [comment]
![prototypeDEBUG2024-04-0214-19-34-ezgif com-video-to-gif-converter](https://github.com/Sacolle/Gamejam/assets/55171112/20180aba-b7b4-491e-bb04-20e09fb32507)

apertando ESC menu

**Comment by beersprite** [comment]
Completed on PR #26
