### ISSUE TITLE
Adicionar as telas de inicio e fim ao workflow do jogo

### ISSUE THREAD

**Issue by Sacolle** [Sacolle/Gamejam#29]

**Comment by Sacolle** [comment]
Dentro da main tem um elemento chamado KillBox, ele tem um sinal linkado no script da main. Quando algo entra na área, fim de jogo

**Comment by beersprite** [comment]
- Início do Jogo já tem (menu.tscn)
- GameOver já tem, mas precisa ter a lógica do reset do jogo
- Falta tela do final do jogo

A lógica do reset pode usar pra todas
